module.exports = {
  /* jQuery Events http://goo.gl/6DOW */
  blur: true,
  change: true,
  click: true,
  contextmenu: true,
  dblclick: true,
  focus: true,
  focusin: true,
  focusout: true,
  hover: true,
  keydown: true,
  keypress: true,
  keyup: true,
  mousedown: true,
  mouseenter: true,
  mouseleave: true,
  mousemove: true,
  mouseout: true,
  mouseover: true,
  mouseup: true,
  resize: true,
  scroll: true,
  select: true,
  submit: true
}
