module.exports = {
  /* HTMLElement https://goo.gl/JN4Q1e */
  onabort: true,
  onblur: true,
  onchange: true,
  onclick: true,
  onclose: true,
  oncontextmenu: true,
  oncopy: true,
  oncut: true,
  ondblclick: true,
  onerror: true,
  onfocus: true,
  oninput: true,
  onkeydown: true,
  onkeypress: true,
  onkeyup: true,
  onload: true,
  onmousedown: true,
  onmousemove: true,
  onmouseout: true,
  onmouseover: true,
  onmouseup: true,
  onpaste: true,
  onpointercancel: true,
  onpointerdown: true,
  onpointerenter: true,
  onpointerleave: true,
  onpointermove: true,
  onpointerout: true,
  onpointerover: true,
  onpointerup: true,
  onreset: true,
  onresize: true,
  onscroll: true,
  onselect: true,
  onselectstart: true,
  onsubmit: true,
  ontouchcancel: true,
  ontouchmove: true,
  ontouchstart: true,

  /* Element https://goo.gl/47RL2l */
  ongotpointercapture: true,
  onlostpointercapture: true,
  onwheel: true
}
